### ISSUE TITLE
Vullen stermodel

### ISSUE THREAD

**Issue by jvlith** [NLHEALTHCARE/PYELT#17]
Overwegen om alles dagelijks te droppen en weer opnieuw op te bouwen.

- Alter statement is niet meer nodig

**Comment by dkapitan** [comment]
@jvlith dit ticket past beter in workflow van https://github.com/NLHEALTHCARE/CLINICSVAULT denk ik

**Comment by jvlith** [comment]
> @jvlith dit ticket past beter in workflow van https://github.com/NLHEALTHCARE/CLINICSVAULT  denk ik

eens
