### ISSUE TITLE
PostgreSQL performance optimalisatie

### ISSUE THREAD

**Issue by dkapitan** [NLHEALTHCARE/PYELT#22]
Op basis van eerste kijk in DV, valt mij op dat sommige views (b.v. patient_view) langzaam zijn (8 tot 10 seconden).

Ik vermoed dat we met PostgreSQL performance tuning veel verbetering kunnen doen:
- waar zetten we indexes op?
- welke soort index gebruiken we?
- hoe doen we trade-off tussen read-snelheid vs insert-snelheid
- kunnen views van entiteiten nog geoptimaliseerd worden, b.v. wanneer er veel hybrid sats --> index op type kolom

Denk/doe/kijk graag mee.

**Comment by dkapitan** [comment]
@hvanreenen 
Ik heb wat testen gedaan en gegoogled. De eerste optimalisatie die ik heb gevonden is een aparte index op 'type' kolom in hyrid sats. Actual query time gaat hiermee ongeveer factor 3 sneller.

'Type' heb je al opgenomen in de primary key, maar omdat we daar apart op joinen in de views, is volgens mij een aparte index een goede oplossing, met relatief weinig extra overhead.

**Comment by hvanreenen** [comment]
index is toegevoegd aan de gegenereerde ddl in pyelt. Bij nieuwe dv zal dit actueel worden

**Comment by dkapitan** [comment]
@hvanreenen 
Volgende simpele index die veel zal schelen:
`create index _ref_values.valueset_naam`

Hier wordt ook veel op gejoined in de views, om codes te maken.

Daarnaast is de vraag: wil je alle kolommen uit een sat die naar ` _ref_values` verwijzen niet ook een index geven, dus:
`create index subtraject_sat.zortype` etc.

**Comment by dkapitan** [comment]
Index op boolean `_active` is wel beter: bijvoorbeeld bij `afspraak` zijn er veel inactive

**Comment by hvanreenen** [comment]
heb je getest of indexeren uitmaakt van de ref_- code velden, zoals subtraject_sat.zortype  ?
Zo ja, maakt dat veel uit?

**Comment by dkapitan** [comment]
Wat mij ook opvalt:

- index op de hubs is op `_id` als single column
- index op de sats zijn multiple columns, dus `primary key(_id, _runid)`

Als je met queryen alleen joined op sat._id dan wordt de index niet gebruikt. Ik ga even testen of dit inderdaad zo is.

Net gechecked: marginaal effect. PostgreSQL documentatie zegt dat de [engine dit zelf oplost ](https://www.postgresql.org/docs/9.6/static/indexes-multicolumn.html):

> A multicolumn B-tree index can be used with query conditions that involve any subset of the index's columns, but the index is most efficient when there are constraints on the leading (leftmost) columns.

**Comment by dkapitan** [comment]
Even een checklist bijhouden van alle indexen die positief effect hebben (check betekent al opgenomen in pyelt codebase):

- [x] `sat.type` bij hybrid sats
- [ ] `sat._active` bij alle sats
- [ ] `_ref_values.valueset_naam`
- [ ] `.sat.ref_code_veld` bij alle sats

**Comment by hvanreenen** [comment]
Done. Bij nieuwe dv zal het actief zijn

Nu wel kijken of insert niet te traag gaat worden, Zo ja, dan optie testen om eerst alle indexes weg te gooien, dan te inserten en dan opnieuw de indexes aan te maken.
