### ISSUE TITLE
COPY ombouwen naar \copy

### ISSUE THREAD

**Issue by jellescheurwater** [NLHEALTHCARE/PYELT#23]
Bij het draaien van de DV op turing-prod blijven er errors komen vanwege het COPY commando van de files op /tmp/pyelt/data_transfer met de volgende melding (Bijvoorbeeld, hij doet het bij alle copies):
```
SQL: COPY sor_timeff.afspraak_deelnemer_temp (ifev_id,agb_code,ifev_rel_nr,ifam_mdw_id,ifam_ev_id,ifam_hoedanigheid,ifam_eigenaar_type) FROM  '/tmp/pyelt/datatransfer/NLHP/view_afspraak_deelnemer.csv' DELIMITER ';' CSV HEADER;

ERROR: must be superuser to COPY to or from a file
HINT:  Anyone can COPY to stdout or from stdin. psql's \copy command also works for anyone.
```
Zou jij het COPY statement om kunnen bouwen naar \copy, zodat de DV ook onder applicatie-user kan draaien en niet alleen onder super-users?

**Comment by hvanreenen** [comment]
@jellescheurwater, Ik had ook je voicemail ingesproken. Graag even overleg over deze issue.

**Comment by jellescheurwater** [comment]
Volgens mij draait alles tegenwoordig toch onder de applicatiegebruiker _dwh2_ ?
Zolang alles inderdaad op de server werkt onder de gebruiker _dwh2_ (= geen superuser) dan is deze issue obsolete.

**Comment by hvanreenen** [comment]
Toch even overleg hierover, volgens mij had het ermee te maken dat we gedwongen zijn /tmp/ te gebruiken omdat de user dhw2 geen rechten heeft op andere paden vanuit postgres....(voor mij geen probleem /tmp/ te gebruiken.)

**Comment by hvanreenen** [comment]
Treedt niet meer op, is geen issue meer. Kan lezen en schrijven vanaf /tmp
