### ISSUE TITLE
Alter statements in dimension table

### ISSUE THREAD

**Issue by hvanreenen** [NLHEALTHCARE/PYELT#5]
in /pyelt/process/ddl.py functie create_or_alter_dim

Toevoegen alter statement voor als er velden bij zijn gekomen.

Zie __create_or_alter_sat()

**Comment by hvanreenen** [comment]
Ook voor facttables: create_or_alter_fact()

**Comment by jvlith** [comment]
@hvanreenen :
m.b.t. het type in casus van een DmReference column heb ik hardcoded integer genomen omdat het volgens mij altijd zo is en ik er niet met een andere weg kan komen. Is dit juist en/of zijn er nog betere alternatieven

```
            for col_name, col in fact_cls.__ordereddict__.items():
                if isinstance(col, Column):
                    if not col_name in refected_column_names:
                        add_fields += 'ADD COLUMN {} {}, '.format(col.name, col.type)
                if isinstance(col, DmReference):
                    if not col_name in refected_column_names:
                        add_fields += 'ADD COLUMN {} {}, '.format(col.get_fk_field_name(),'integer')
```

**Comment by jvlith** [comment]
create_or_alter_fact() en create_or_alter_dim() is gepushed

**Comment by hvanreenen** [comment]
helemaal goed
