### ISSUE TITLE
Error bij het aftrappen bash script

### ISSUE THREAD

**Issue by jvlith** [NLHEALTHCARE/PYELT#9]
Hoi Hj,

Zie hieronder 

'error: insufficient permission for adding an object to repository database .git/objects'

is dit jou bekend?

dwh2_clinics@shannon-dev:/opt/dwh2> crontab -l
00 01 \* \* \* bash /opt/dwh2/pull_and_run.sh   >/dev/null 2>$1
dwh2_clinics@shannon-dev:/opt/dwh2> sh pull_and_run.sh
remote: Counting objects: 76, done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 76 (delta 36), reused 5 (delta 5), pack-reused 13
error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed
remote: Counting objects: 20, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 20 (delta 0), reused 0 (delta 0), pack-reused 15
error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed
remote: Counting objects: 129, done.
remote: Compressing objects: 100% (89/89), done.
Receiving objects: 100% (129/129), 40.00 KiB | 0 bytes/s, done.
remote: Total 129 (delta 74), reused 17 (delta 17), pack-reused 23
Resolving deltas: 100% (84/84), completed with 12 local objects.
From https://github.com/NLHEALTHCARE/PYELT
- branch            HEAD       -> FETCH_HEAD
  Updating fe8f83e..f00eb46
  Fast-forward
  pyelt/datalayers/dm.py                           |  61 +++
  pyelt/datalayers/dwh.py                          |   7 +
  pyelt/helpers/validations.py                     |   2 +-
  pyelt/mappings/dv_to_datamart_mappings.py        |  50 +-
  pyelt/mappings/sor_to_dv_mappings.py             | 629 ++---------------------
  pyelt/pipeline.py                                |  43 +-
  pyelt/process/base.py                            |  27 +-
  pyelt/process/ddl.py                             |  84 ++-
  pyelt/process/etl.py                             |   3 +-
  tests/data/zorgverleners3_rob.csv                |   2 +-
  tests/unit_tests_rob/global_test_suite.py        |   3 +-
  tests/unit_tests_rob/json_to_postgres.py         |  49 ++
  tests/unit_tests_rob/mappings_rob_hybridlinks.py |  28 +-
  tests/unit_tests_rob/test05r_process.py          |  29 +-
  tests/unit_tests_rob/test06r_hybridlinks.py      |  16 +-
  tests/unit_tests_rob/test07r_jsonb.py            | 210 ++++++++
  tests/unit_tests_rob/test_domain.py              |  48 ++
  tests/unit_tests_rob/test_mappings.py            |  48 ++
  tests/unit_tests_rob/tester.py                   |  67 +++
  19 files changed, 743 insertions(+), 663 deletions(-)
  create mode 100644 pyelt/datalayers/dm.py
  create mode 100644 tests/unit_tests_rob/json_to_postgres.py
  create mode 100644 tests/unit_tests_rob/test07r_jsonb.py
  create mode 100644 tests/unit_tests_rob/test_domain.py
  create mode 100644 tests/unit_tests_rob/test_mappings.py
  create mode 100644 tests/unit_tests_rob/tester.py

**Comment by hvanreenen** [comment]
Heb owner aangepast naar dwh2_clinics. Kijken of het morgen wel goed gaat.

**Comment by jvlith** [comment]
die initiele errors zie ik nu niet dus lijkt goed te gaan

**Comment by hvanreenen** [comment]
treedt niet meer op
